services:

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6999:6333"
    restart: always
    volumes:
      - ./qdrant_data:/qdrant/storage

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: manga_db
      POSTGRES_USER: user_api
      POSTGRES_PASSWORD: secret
    ports:
      - "5444:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mangaverse.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5052:80"
    depends_on:
      - postgres
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
